sudo: required
dist: trusty

language: cpp

git:
    depth: 1

before_install:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update --fix-missing
    - sudo apt-get install -qq
        clang
        libfreetype6-dev
        libx11-dev
        libstdc++6
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
        libwebkit2gtk-4.0 
        libgtk-3-dev
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq

compiler:
    - clang++

branches:
    only:
        - master

script:
    - make -C projects/standalone/TravisCI/LinuxMakefile/

